# Generated by Django 2.2.2 on 2019-06-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='word',
            name='identifier',
            field=models.CharField(default='', max_length=20),
        ),
    ]
