# Generated by Django 2.2.2 on 2019-07-04 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20190629_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='translation',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=models.CharField(max_length=500),
        ),
    ]
