# Generated by Django 2.2.2 on 2019-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20190704_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
